In [ ]:
# /* PART 2: SQLite
# We now want you to jump over to a local instance of the database on your machine. 
#Copy and paste the LocalSQLConnection.py script into an empty Jupyter notebook, and run it. 
#Make sure that the SQLFiles folder containing thes files is in your working directory, and
#that you haven't changed the name of the .db file from 'sqlite\db\pythonsqlite'.
#You should see the output from the initial query 'SELECT * FROM FACILITIES'.
#Complete the remaining tasks in the Jupyter interface. If you struggle, feel free to go back
#to the PHPMyAdmin interface as and when you need to. 
#You'll need to paste your query into value of the 'query1' variable and run the code block again to get an output.

In [15]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT * FROM FACILITIES;"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [6]:
#Q10: Produce a list of facilities with a total revenue less than 1000.
#The output of facility name and total revenue, sorted by revenue. 
#Remember that there's a different cost for guests and members!

In [20]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT name,
    revenue
FROM
    (SELECT
    name,
    SUM(CASE WHEN memid = 0 THEN guestcost * slots 
        ELSE membercost * slots END) AS revenue
    FROM `Bookings` AS b
    INNER JOIN `Facilities` AS f
        ON b.facid = f.facid
    GROUP BY name)
WHERE revenue < 1000
ORDER BY revenue;
"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [21]:
#Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [22]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT surname,
        firstname,
        (SELECT surname || ' ' || firstname 
        FROM `Members` 
        WHERE m2.recommendedby != '' 
            AND memid = m2.recommendedby) AS recommendedby
FROM `Members` as m2
ORDER BY surname, firstname;"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader', 'Florence', 'Stibbons Ponder')
('Baker', 'Anne', 'Stibbons Ponder')
('Baker', 'Timothy', 'Farrell Jemima')
('Boothe', 'Tim', 'Rownam Tim')
('Butters', 'Gerald', 'Smith Darren')
('Coplin', 'Joan', 'Baker Timothy')
('Crumpet', 'Erica', 'Smith Tracy')
('Dare', 'Nancy', 'Joplette Janice')
('Farrell', 'David', None)
('Farrell', 'Jemima', None)
('GUEST', 'GUEST', None)
('Genting', 'Matthew', 'Butters Gerald')
('Hunt', 'John', 'Purview Millicent')
('Jones', 'David', 'Joplette Janice')
('Jones', 'Douglas', 'Jones David')
('Joplette', 'Janice', 'Smith Darren')
('Mackenzie', 'Anna', 'Smith Darren')
('Owen', 'Charles', 'Smith Darren')
('Pinker', 'David', 'Farrell Jemima')
('Purview', 'Millicent', 'Smith Tracy')
('Rownam', 'Tim', None)
('Rumney', 'Henrietta', 'Genting Matthew')
('Sarwin', 'Ramnaresh', 'Bader Florence')
('Smith', 'Darren', None)
('Smith', 'Darren', None)
('Smith', 'Jack', 'Smith Darren')
('Smith', 'Tracy', None)
('Stibbons', 'Ponder', 'Tracy Burton')
('Tracy', 'Burton', None)
('Tupperware', 'Hyacinth', None)
('Worthington-Smyth', 'Henry', 'Smith Tracy')

In [23]:
#Q12: Find the facilities with their usage by member, but not guests

In [24]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT (SELECT name 
        FROM `Facilities` 
        WHERE facid = b.facid) AS name,
        SUM(slots) AS memberusage
FROM `Bookings` AS b
WHERE memid != 0
GROUP BY name;
"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Massage Room 1', 884)
('Massage Room 2', 54)
('Pool Table', 856)
('Snooker Table', 860)
('Squash Court', 418)
('Table Tennis', 794)
('Tennis Court 1', 957)
('Tennis Court 2', 882)

In [25]:
#Q13: Find the facilities usage by month, but not guests

In [26]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT (SELECT name 
        FROM `Facilities` 
        WHERE facid = b.facid) AS name,
        strftime('%m',starttime) AS month,
        SUM(slots) AS memberusage
FROM `Bookings` AS b
WHERE memid != 0
GROUP BY name, month;"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', '07', 165)
('Badminton Court', '08', 414)
('Badminton Court', '09', 507)
('Massage Room 1', '07', 166)
('Massage Room 1', '08', 316)
('Massage Room 1', '09', 402)
('Massage Room 2', '07', 8)
('Massage Room 2', '08', 18)
('Massage Room 2', '09', 28)
('Pool Table', '07', 110)
('Pool Table', '08', 303)
('Pool Table', '09', 443)
('Snooker Table', '07', 140)
('Snooker Table', '08', 316)
('Snooker Table', '09', 404)
('Squash Court', '07', 50)
('Squash Court', '08', 184)
('Squash Court', '09', 184)
('Table Tennis', '07', 98)
('Table Tennis', '08', 296)
('Table Tennis', '09', 400)
('Tennis Court 1', '07', 201)
('Tennis Court 1', '08', 339)
('Tennis Court 1', '09', 417)
('Tennis Court 2', '07', 123)
('Tennis Court 2', '08', 345)
('Tennis Court 2', '09', 414)